function plot_canopyheight_h5_4bands()
% Plot 4 canopy height bands from global HDF5 (1800x3600)
% Uses the HDF5 generated by processHveg.m:
%   datasets:
%     /H_forest, /H_shrub, /H_herb, /H_mix (single, 1800x3600)
%     /lat_center (1800x1), /lon_center (3600x1)
%
% Missing values are stored as NaN.

h5file = "G:\data\CanopyHeight\ETH_global_reprocess\Hveg_01Deg.h5";

ds = { ...
    "/H_forest", ...
    "/H_shrub", ...
    "/H_herb", ...
    "/H_mix" ...
};

titles = { ...
    "Forest mean canopy height (0.1°)", ...
    "Shrub mean canopy height (0.1°)", ...
    "Herb mean canopy height (0.1°)", ...
    "Mix mean canopy height (0.1°)" ...
};

% --- read axes from file ---
lat = h5read(h5file, "/lat_center");  % 1800x1
lon = h5read(h5file, "/lon_center");  % 3600x1
lat = double(lat(:))';
lon = double(lon(:))';

% --- basic checks ---
nRows = numel(lat);
nCols = numel(lon);
fprintf("H5 grid: %d x %d\n", nRows, nCols);

for i = 1:4
    A = h5read(h5file, ds{i});   % expected 1800x3600 single
    A = double(A);

    if ~isequal(size(A), [nRows nCols])
        error("Dataset %s has size %s, but lat/lon imply %dx%d.", ...
            ds{i}, mat2str(size(A)), nRows, nCols);
    end

    % A already uses NaN for missing; keep as-is
    figure("Color","w","Name",titles{i});
    imagesc(lon, lat, A);
    set(gca, "YDir", "normal"); % lat increases upward
    axis tight;
    xlabel("Longitude"); ylabel("Latitude");
    title(titles{i});

    colorbar;

    % Optional: clip display range
    % caxis([0 60]);

    % Print quick stats without mean() (avoid name shadowing)
    validMask = ~isnan(A);
    if any(validMask(:))
        v = A(validMask);
        fprintf("[%s] min=%.3f, median=%.3f, max=%.3f, NaN ratio=%.4f\n", ...
            ds{i}, min(v), median(v), max(v), sum(isnan(A(:)))/numel(A));
    else
        fprintf("[%s] all NaN\n", ds{i});
    end
end

end
